export interface NavItem {
  id: string;
  label: string;
  en: string;
  level?: "基础" | "进阶" | "高级";
}
export interface NavGroup {
  id: string;
  index: string;
  title: string;
  items: NavItem[];
}

export const NAV: NavGroup[] = [
  {
    id: "foundations",
    index: "01",
    title: "设计基础",
    items: [
      { id: "color", label: "色彩系统", en: "Color" },
      { id: "typography", label: "排版层级", en: "Typography" },
      { id: "spacing", label: "间距与栅格", en: "Spacing" },
      { id: "elevation", label: "圆角阴影层级", en: "Elevation" },
      { id: "motion-tokens", label: "动效令牌", en: "Motion" },
      { id: "states", label: "交互状态", en: "States" },
    ],
  },
  {
    id: "general",
    index: "02",
    title: "基础组件",
    items: [
      { id: "button", label: "按钮", en: "Button" },
      { id: "segmented", label: "分段控制器", en: "Segmented", level: "进阶" },
      { id: "badge", label: "徽章标签角标", en: "Badge Tag" },
      { id: "avatar", label: "头像", en: "Avatar" },
      { id: "tooltip", label: "工具提示", en: "Tooltip" },
      { id: "tag-input", label: "标签输入", en: "Tag Input", level: "进阶" },
      { id: "number-input", label: "数字步进器", en: "Number Input", level: "进阶" },
      { id: "countdown-button", label: "倒计时按钮", en: "Countdown", level: "进阶" },
      { id: "split-button", label: "分割按钮", en: "Split Button", level: "进阶" },
    ],
  },
  {
    id: "forms",
    index: "03",
    title: "表单与输入",
    items: [
      { id: "input", label: "输入框", en: "Input" },
      { id: "search", label: "搜索框", en: "Search" },
      { id: "password", label: "密码输入", en: "Password" },
      { id: "floating-label", label: "浮动标签", en: "Floating Label", level: "进阶" },
      { id: "selection", label: "复选 / 单选 / 开关", en: "Selection" },
      { id: "slider", label: "滑块", en: "Slider", level: "进阶" },
      { id: "otp", label: "验证码输入", en: "OTP", level: "进阶" },
      { id: "rating", label: "评分", en: "Rating" },
      { id: "combobox", label: "可搜索下拉", en: "Combobox", level: "进阶" },
      { id: "select", label: "下拉选择", en: "Select" },
      { id: "datepicker", label: "日期选择器", en: "Date Picker", level: "进阶" },
      { id: "dropzone", label: "文件上传区", en: "Dropzone", level: "进阶" },
      { id: "color-swatches", label: "颜色选择", en: "Color Swatches" },
      { id: "multi-select", label: "多选下拉", en: "Multi Select", level: "进阶" },
      { id: "date-range", label: "日期范围选择", en: "Date Range", level: "高级" },
      { id: "form-validation", label: "表单校验", en: "Form Validation", level: "进阶" },
    ],
  },
  {
    id: "navigation",
    index: "04",
    title: "导航",
    items: [
      { id: "navbar", label: "顶部导航栏", en: "Navbar" },
      { id: "tabs", label: "标签页", en: "Tabs", level: "进阶" },
      { id: "breadcrumb", label: "面包屑", en: "Breadcrumb" },
      { id: "pagination", label: "分页", en: "Pagination" },
      { id: "sidebar", label: "侧边栏", en: "Sidebar", level: "进阶" },
      { id: "stepper", label: "步骤条", en: "Stepper" },
      { id: "dropdown", label: "下拉菜单", en: "Dropdown" },
      { id: "command", label: "命令面板 ⌘K", en: "Command Palette", level: "高级" },
      { id: "contextmenu", label: "右键菜单", en: "Context Menu", level: "进阶" },
      { id: "dock", label: "macOS Dock", en: "Dock", level: "高级" },
      { id: "scroll-progress", label: "阅读进度 / 收缩头部", en: "Scroll Progress", level: "进阶" },
      { id: "bottom-tabs", label: "底部标签栏", en: "Bottom Tab Bar", level: "进阶" },
      { id: "notification-panel", label: "通知面板", en: "Notifications", level: "进阶" },
      { id: "scroll-spy-toc", label: "页内目录 · 滚动侦测", en: "Scroll Spy TOC", level: "高级" },
    ],
  },
  {
    id: "feedback",
    index: "05",
    title: "反馈与覆盖层",
    items: [
      { id: "toast", label: "轻提示", en: "Toast", level: "进阶" },
      { id: "modal", label: "对话框 / 确认框", en: "Modal" },
      { id: "drawer", label: "抽屉 / 底部面板", en: "Drawer", level: "进阶" },
      { id: "alert", label: "警告条 / 横幅", en: "Alert" },
      { id: "progress", label: "进度指示", en: "Progress", level: "进阶" },
      { id: "loading", label: "加载态 / 骨架屏", en: "Loading" },
      { id: "empty", label: "空状态", en: "Empty State" },
      { id: "popover", label: "气泡卡片", en: "Popover" },
      { id: "fab", label: "悬浮操作按钮", en: "FAB · Speed Dial", level: "进阶" },
    ],
  },
  {
    id: "data",
    index: "06",
    title: "数据展示",
    items: [
      { id: "card", label: "卡片", en: "Card" },
      { id: "table", label: "数据表格", en: "Table", level: "进阶" },
      { id: "accordion", label: "手风琴", en: "Accordion" },
      { id: "timeline", label: "时间线", en: "Timeline" },
      { id: "stats", label: "指标卡片 / 迷你图", en: "Stats", level: "进阶" },
      { id: "code", label: "代码块 / Kbd", en: "Code Block" },
      { id: "tree", label: "树形视图", en: "Tree", level: "进阶" },
      { id: "kanban", label: "看板拖放", en: "Kanban", level: "高级" },
      { id: "chat", label: "聊天气泡", en: "Chat" },
      { id: "heatmap", label: "日历热力图", en: "Heatmap", level: "进阶" },
      { id: "carousel", label: "轮播", en: "Carousel" },
      { id: "compare", label: "图片对比滑块", en: "Compare", level: "进阶" },
      { id: "bento", label: "Bento 网格", en: "Bento", level: "进阶" },
      { id: "masonry", label: "瀑布流", en: "Masonry", level: "进阶" },
      { id: "description-list", label: "描述列表", en: "Description List" },
      { id: "blockquote", label: "引用块", en: "Blockquote" },
      { id: "virtual-list", label: "虚拟滚动列表", en: "Virtual List", level: "高级" },
      { id: "transfer", label: "穿梭框", en: "Transfer", level: "进阶" },
    ],
  },
  {
    id: "motion",
    index: "07",
    title: "指针交互与背景",
    items: [
      { id: "spotlight-bg", label: "背景随鼠标移动", en: "Spotlight BG", level: "高级" },
      { id: "parallax", label: "鼠标视差", en: "Parallax", level: "进阶" },
      { id: "visualizer", label: "音乐律动条", en: "Visualizer", level: "高级" },
      { id: "magnetic", label: "磁性按钮", en: "Magnetic", level: "进阶" },
      { id: "tilt", label: "3D 倾斜卡片", en: "Tilt", level: "进阶" },
      { id: "spotlight-card", label: "边框聚光卡片", en: "Spotlight Card", level: "高级" },
      { id: "cursor", label: "自定义光标", en: "Cursor", level: "高级" },
      { id: "particles", label: "粒子连线背景", en: "Particles", level: "高级" },
      { id: "ripple", label: "涟漪点击", en: "Ripple" },
      { id: "knob", label: "旋钮", en: "Knob", level: "进阶" },
      { id: "glass", label: "毛玻璃", en: "Glass" },
      { id: "beam", label: "边框光束", en: "Beam", level: "高级" },
      { id: "mesh-gradient", label: "流动渐变背景", en: "Mesh Gradient", level: "进阶" },
    ],
  },
  {
    id: "advanced",
    index: "08",
    title: "文字、滚动与高级模式",
    items: [
      { id: "marquee", label: "无限跑马灯", en: "Marquee" },
      { id: "typewriter", label: "打字机", en: "Typewriter" },
      { id: "scramble", label: "文字乱码解码", en: "Scramble", level: "进阶" },
      { id: "countup", label: "数字滚动", en: "Count Up" },
      { id: "reveal", label: "滚动显现", en: "Reveal" },
      { id: "stack", label: "堆叠卡片", en: "Stack", level: "进阶" },
      { id: "infinite", label: "无限滚动", en: "Infinite Scroll", level: "进阶" },
      { id: "sortable", label: "拖拽排序", en: "Sortable", level: "进阶" },
      { id: "confetti", label: "纸屑庆祝", en: "Confetti", level: "进阶" },
      { id: "swipe", label: "左滑删除", en: "Swipe", level: "高级" },
      { id: "theme-toggle", label: "主题切换转场", en: "View Transition", level: "高级" },
      { id: "clock", label: "时钟", en: "Clock" },
      { id: "gallery", label: "伸缩画廊", en: "Gallery", level: "进阶" },
      { id: "word-reveal", label: "滚动逐字点亮", en: "Text Reveal", level: "进阶" },
      { id: "resizable", label: "可拖拽分栏", en: "Resizable", level: "进阶" },
      { id: "noise", label: "噪点纹理", en: "Noise" },
      { id: "text-highlight", label: "搜索高亮", en: "Text Highlight", level: "进阶" },
    ],
  },
  {
    id: "standards",
    index: "09",
    title: "设计规范标准",
    items: [
      { id: "sizing", label: "触控与尺寸标准", en: "Sizing" },
      { id: "color-standard", label: "色彩使用标准", en: "Color" },
      { id: "type-standard", label: "字阶与行高标准", en: "Type Scale" },
      { id: "z-index", label: "层级 z-index 标准", en: "Elevation" },
      { id: "motion-standard", label: "动效时长标准", en: "Motion" },
      { id: "breakpoints", label: "响应式断点标准", en: "Breakpoints" },
      { id: "keyboard", label: "键盘交互标准", en: "Keyboard" },
    ],
  },
  {
    id: "patterns",
    index: "10",
    title: "模式与原则",
    items: [
      { id: "layout", label: "页面布局骨架", en: "Layout" },
      { id: "responsive", label: "响应式策略", en: "Responsive" },
      { id: "form-ux", label: "表单体验", en: "Form UX" },
      { id: "darkmode", label: "深色模式", en: "Dark Mode" },
      { id: "checklist", label: "设计走查清单", en: "Checklist" },
      { id: "error-pattern", label: "错误与重试模式", en: "Error & Retry" },
    ],
  },
];
